version: "3"
services:
  mysql:
    build:
      context: ./docker/mysql
    image: williamsilva808:mysql-5.7
    container_name: database_mysql
    restart: always
    ports:
      - "3306:3306"    
    environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: application
    volumes:
      - ./mysql/data:/var/lib/mysql
    networks:
      - site
  php:
    build:
      context: ./docker/php
    image: williamsilva808:php-7.1
    container_name: application
    depends_on:
      - mysql    
    environment:
      DB_HOST: 'mysql'
      DB_PORT: '3306'
      DB_DATABASE: 'site'
      DB_USERNAME: 'root'
      DB_PASSWORD: 'root'
      DEBUG: 'true'
    volumes:
      - ./:/var/www/html
    networks:
      - site

  web:
    image: nginx:alpine
    container_name: nginx
    depends_on:
      - php
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - site
networks:
  site:
    driver: bridge
